services:

  mysql:
    image: mysql:8.0

    container_name: reputation_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reputation_db
      MYSQL_USER: reputation_user
      MYSQL_PASSWORD: reputation_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes: 
      - ./uploads:/app/uploads

    container_name: reputation_app

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "5000:5000"

    depends_on:
      - mysql

volumes:
  mysql_data: